package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;
import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated by tools/generate_plugins.dart - DO NOT EDIT
 * Stub version for compilation - real plugins loaded via reflection
 */
@Keep
public final class GeneratedPluginRegistrant {
    private static final String TAG = "GeneratedPluginRegistrant";

    public static void registerWith(@NonNull FlutterEngine flutterEngine) {
        // Plugins registered dynamically by Flutter engine at runtime
        // See .flutter-plugins-dependencies for the real plugin list
    }
}
